### ISSUE TITLE
Make testrpc a module

### ISSUE THREAD

**Issue by ajunge** [ConsenSys/eth-testrpc#1]
Hi, 
I think something is missing in the install instructions. I follow them and I got the error:

```
$ python testrpc.py
Traceback (most recent call last):
  File "testrpc.py", line 3, in <module>
    from jsonrpclib.SimpleJSONRPCServer import SimpleJSONRPCServer
ImportError: No module named jsonrpclib.SimpleJSONRPCServer
```

**Comment by ajunge** [comment]
Fixed with 

```
pip install jsonrpclib
```

**Comment by AFDudley** [comment]
Looks like the requirements file is missing, as well as the rest of the scaffolding to make testrpc a module. I would consider those two different feature requests :)

**Comment by tcoulter** [comment]
I don't know how to do those things without researching it. Any python expert wanna take a crack at it?

**Comment by tcoulter** [comment]
I edited the README to include `pip install jsonrpclib` for the time being.

**Comment by tcoulter** [comment]
Thanks @AFDudley!

**Comment by caktux** [comment]
will take a look at it, this is too useful not to be a module and published on pypi :) the former would only require to `touch __init__.py` and commit that file, the latter just a tiny bit more work

**Comment by tcoulter** [comment]
Awesome, thanks @caktux!

**Comment by tcoulter** [comment]
This is done. Thanks @ryepdx for your help.

**Comment by ryepdx** [comment]
No problem! Glad to see it's up on PyPI now. :-)
