### ISSUE TITLE
Change JSON-RPC libraries?

### ISSUE THREAD

**Issue by ryepdx** [ConsenSys/eth-testrpc#17]
I'm trying to use Test RPC in conjunction with my gulp-ethertest tool, but it looks like jsonrpclib is pretty easily brought to its knees by simple test cases. In particular, jsonrpclib *seems* to have a request-prioritization problem that leads to early requests for filter logs to be drowned out by block filter watchers. In a private testing environment, requests would ideally be handled in a more-or-less-FIFO order. (Which is to be expected in a multi-threaded server, of course, but parallel request processing is really not a positive in this case.)

Alternatively, introducing an optional delay between mining blocks might help.

**Comment by tcoulter** [comment]
Hmm. This is a good question. Are you using batch JSON RPC requests (i.e., one request, array of payloads), or are your requests individually sent in parallel? 

If using batch requests, the JSON RPC spec says that implementations are free to run the requests in parallel. If you're sending them individually, you might consider waiting for the first one to complete before sending the next (as you'd likely need to do with geth anyway). Would need an example to make a better recommendation, however.

**Comment by tcoulter** [comment]
Link to spec: http://www.jsonrpc.org/specification#batch

**Comment by ryepdx** [comment]
I'm just using web3. I haven't yet checked to see if geth is similarly impeded.

**Comment by tcoulter** [comment]
Can you point me to the code in your app that's having the issue? I noticed it was on /r/ethereum recently. A github link would be great.

**Comment by ryepdx** [comment]
Sure. I'll clean it up a little first, as I don't want to reveal what I'm working on yet, and then I'll link you to it.

**Comment by tcoulter** [comment]
Ah, makes sense. Thanks.

**Comment by ryepdx** [comment]
Okay, so this should demonstrate the problem: https://github.com/ryepdx/welcometothejungle

It will eventually return the results expected when you run "gulp test", but it'll take much longer than it should. Additionally, if you comment out the "watchLogEvents: false" line (#100) in gulpfile.js, it'll run one contract's tests and then just stop. This doesn't happen with geth, which makes me suspect it's a problem with Test RPC.

I surmised that the problem appeared to be jsonrpclib by putting debug output lines in LogFilter.getChanges to see when the event filters got requested first, and in node_modules/web3/lib/web3/httpprovider.js to see when the request for the event filters first went out and when that particular request (as tagged by the JSON-RPC request's `id` property) finally was responded to by Test RPC. From that I was able to tell that the request for the event logs went out almost immediately and that the event logs were returned just as quickly from the LogFilter object, but then the JSON-RPC response ended up taking a very long time to come back. So while I can't point to *where* in jsonrpclib the problem is, I have a very strong suspicion that is *is* in jsonrpclib.

**Comment by ryepdx** [comment]
I was able to rewrite my testing tool to use only one watcher each for every event type and cut down on the number of transaction receipt requests it was making. Seems to have resolved the issue for me, at least for the time being.

**Comment by tcoulter** [comment]
Sorry I wasn't able to take a look at this - got really backed up this week. Let me know if you'd still like me know if you run into anymore trouble.

**Comment by ryepdx** [comment]
No worries. I think it's a mixed bag, honestly. Reality is that over-chatty
dapps *should* fail, because they'll end up failing in the wild. But on the
other hand, it does detract from pure "contract logic only" tests.
