### ISSUE TITLE
README instructions outdated

### ISSUE THREAD

**Issue by ajunge** [ConsenSys/eth-testrpc#9]
Don't know how to run it anymore.

**Comment by tcoulter** [comment]
Yes - that was a change made today. Sorry about that! 

To run it (for now):

```
$ cd <testrpc checkout>/testrpc
$ python .
```

This is all in preparation to install the testrpc via `pip`. Will have updates on this soon.

**Comment by ajunge** [comment]
Thanxs

**Comment by tcoulter** [comment]
The Readme should still change. Thanks for the report. Reopening as a reminder to fix the readme.

**Comment by tcoulter** [comment]
Done. Thanks!
